"""initial migration

Revision ID: f70661c2dc82
Revises: 
Create Date: 2026-10-06 22:37:51.427907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f70661c2dc82'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category'))
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('sku', name=op.f('uq_products_sku'))
    )
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.CheckConstraint('email IS NOT NULL OR phone IS NOT NULL', name=op.f('ck_suppliers_check_supplier_contact_info')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers'))
    )
    op.create_table('warehouse',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warehouse'))
    )
    op.create_table('category_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_category_products_category_id_category')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_category_products_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category_products'))
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('external_reference_id', sa.String(), nullable=False),
    sa.Column('order_status', sa.String(), nullable=False),
    sa.Column('payment_status', sa.String(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], name=op.f('fk_orders_warehouse_id_warehouse')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('external_reference_id', name=op.f('uq_orders_external_reference_id'))
    )
    op.create_table('stock',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('reorder_threshold', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stock_product_id_products')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], name=op.f('fk_stock_warehouse_id_warehouse')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock'))
    )
    op.create_table('supplier_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('supplier_sku', sa.String(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('time_required_in_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_supplier_products_product_id_products')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_supplier_products_supplier_id_suppliers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_products'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], name=op.f('fk_users_warehouse_id_warehouse')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('delivery',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('delivery_address', sa.Text(), nullable=False),
    sa.Column('delivery_for', sa.String(), nullable=False),
    sa.Column('delivered_to', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], name=op.f('fk_delivery_agent_id_users')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_delivery_order_id_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delivery'))
    )
    op.create_table('financial_ledger',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_mode', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('parent_transaction_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_financial_ledger_order_id_orders')),
    sa.ForeignKeyConstraint(['parent_transaction_id'], ['financial_ledger.id'], name=op.f('fk_financial_ledger_parent_transaction_id_financial_ledger')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_ledger')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_financial_ledger_idempotency_key')),
    sa.UniqueConstraint('transaction_id', name=op.f('uq_financial_ledger_transaction_id'))
    )
    op.create_table('order_contains',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_contains_order_id_orders')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_order_contains_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_contains'))
    )
    op.create_table('purchase_order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('is_auto_generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'AMENDMENT_REVIEW', name='purchase_order_approval_status'), server_default='PENDING_APPROVAL', nullable=False),
    sa.Column('status', sa.Enum('NOT_ISSUED', 'ISSUED_TO_VENDOR', 'IN_TRANSIT', 'PARTIALLY_RECEIVED', 'FULLY_RECEIVED', 'CLOSED', name='purchase_order_status'), server_default='NOT_ISSUED', nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_purchase_order_approved_by_users')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_purchase_order_created_by_users')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_purchase_order_supplier_id_suppliers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_order'))
    )
    op.create_table('stock_ledger',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('change_quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('reference_type', sa.Enum('ORDER', 'PURCHASE_ORDER', 'TRANSFER', 'RETURN', 'CANCELLATION', 'MANUAL_ADJUSTMENT', name='stock_ledger_refernce_type_enum'), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.Enum('STOCK_IN', 'STOCK_OUT', 'ADJUSTMENT_UP', 'ADJUSTMENT_DOWN', name='stock_ledger_transaction_type_enum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stock_ledger_product_id_products')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_stock_ledger_user_id_users')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], name=op.f('fk_stock_ledger_warehouse_id_warehouse')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_ledger'))
    )
    op.create_table('transfer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_warehouse_id', sa.Integer(), nullable=False),
    sa.Column('destination_warehouse_id', sa.Integer(), nullable=False),
    sa.Column('initiated_by', sa.Integer(), nullable=False),
    sa.Column('transport_mode', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expected_completion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['destination_warehouse_id'], ['warehouse.id'], name=op.f('fk_transfer_destination_warehouse_id_warehouse')),
    sa.ForeignKeyConstraint(['initiated_by'], ['users.id'], name=op.f('fk_transfer_initiated_by_users')),
    sa.ForeignKeyConstraint(['source_warehouse_id'], ['warehouse.id'], name=op.f('fk_transfer_source_warehouse_id_warehouse')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transfer'))
    )
    op.create_table('cancellation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('cancelled_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('financial_ledger_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cancelled_by'], ['users.id'], name=op.f('fk_cancellation_cancelled_by_users')),
    sa.ForeignKeyConstraint(['financial_ledger_id'], ['financial_ledger.id'], name=op.f('fk_cancellation_financial_ledger_id_financial_ledger')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_cancellation_order_id_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cancellation'))
    )
    op.create_table('purchase_order_contains',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('quantity_ordered', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('expected_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_purchase_order_contains_product_id_products')),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], name=op.f('fk_purchase_order_contains_purchase_order_id_purchase_order')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], name=op.f('fk_purchase_order_contains_warehouse_id_warehouse')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_order_contains'))
    )
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_contains_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expire_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['order_contains_id'], ['order_contains.id'], name=op.f('fk_reservation_order_contains_id_order_contains')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_reservation_order_id_orders')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_reservation_product_id_products')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], name=op.f('fk_reservation_warehouse_id_warehouse')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservation'))
    )
    op.create_table('returns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('financial_ledger_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('return_type', sa.String(), nullable=False),
    sa.Column('replacement_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['financial_ledger_id'], ['financial_ledger.id'], name=op.f('fk_returns_financial_ledger_id_financial_ledger')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_returns_order_id_orders')),
    sa.ForeignKeyConstraint(['replacement_order_id'], ['orders.id'], name=op.f('fk_returns_replacement_order_id_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_returns'))
    )
    op.create_table('transfer_contains',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_dispatched', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_transfer_contains_product_id_products')),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfer.id'], name=op.f('fk_transfer_contains_transfer_id_transfer')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transfer_contains'))
    )
    op.create_table('purchase_order_receipts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_contains_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_received', sa.Integer(), nullable=False),
    sa.Column('condition_notes', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_purchase_order_receipts_product_id_products')),
    sa.ForeignKeyConstraint(['purchase_order_contains_id'], ['purchase_order_contains.id'], name=op.f('fk_purchase_order_receipts_purchase_order_contains_id_purchase_order_contains')),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], name=op.f('fk_purchase_order_receipts_purchase_order_id_purchase_order')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_order_receipts'))
    )
    op.create_table('return_contains',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('return_id', sa.Integer(), nullable=False),
    sa.Column('order_contains_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('quantity_expected', sa.Integer(), nullable=False),
    sa.Column('return_unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['order_contains_id'], ['order_contains.id'], name=op.f('fk_return_contains_order_contains_id_order_contains')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_return_contains_product_id_products')),
    sa.ForeignKeyConstraint(['return_id'], ['returns.id'], name=op.f('fk_return_contains_return_id_returns')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], name=op.f('fk_return_contains_warehouse_id_warehouse')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_return_contains'))
    )
    op.create_table('transfer_receipt',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('transfer_contains_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_received', sa.Integer(), nullable=False),
    sa.Column('received_by', sa.Integer(), nullable=False),
    sa.Column('arrived_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_transfer_receipt_product_id_products')),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], name=op.f('fk_transfer_receipt_received_by_users')),
    sa.ForeignKeyConstraint(['transfer_contains_id'], ['transfer_contains.id'], name=op.f('fk_transfer_receipt_transfer_contains_id_transfer_contains')),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfer.id'], name=op.f('fk_transfer_receipt_transfer_id_transfer')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transfer_receipt'))
    )
    op.create_table('return_reciepts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('return_id', sa.Integer(), nullable=False),
    sa.Column('return_contains_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_received', sa.Integer(), nullable=False),
    sa.Column('condition_status', sa.String(), nullable=False),
    sa.Column('condition_notes', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('received_by', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_return_reciepts_product_id_products')),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], name=op.f('fk_return_reciepts_received_by_users')),
    sa.ForeignKeyConstraint(['return_contains_id'], ['return_contains.id'], name=op.f('fk_return_reciepts_return_contains_id_return_contains')),
    sa.ForeignKeyConstraint(['return_id'], ['returns.id'], name=op.f('fk_return_reciepts_return_id_returns')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_return_reciepts'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('return_reciepts')
    op.drop_table('transfer_receipt')
    op.drop_table('return_contains')
    op.drop_table('purchase_order_receipts')
    op.drop_table('transfer_contains')
    op.drop_table('returns')
    op.drop_table('reservation')
    op.drop_table('purchase_order_contains')
    op.drop_table('cancellation')
    op.drop_table('transfer')
    op.drop_table('stock_ledger')
    op.drop_table('purchase_order')
    op.drop_table('order_contains')
    op.drop_table('financial_ledger')
    op.drop_table('delivery')
    op.drop_table('users')
    op.drop_table('supplier_products')
    op.drop_table('stock')
    op.drop_table('orders')
    op.drop_table('category_products')
    op.drop_table('warehouse')
    op.drop_table('suppliers')
    op.drop_table('products')
    op.drop_table('category')
    # ### end Alembic commands ###
